### Different File Loading in Pandas

In [2]:
import pandas as pd

df = pd.read_csv("student_data.csv")
# print(df)
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [2]:
print(type(df['StudentID']))

<class 'pandas.core.series.Series'>

In [3]:
read_excl = pd.read_excel("phitron_student_marks.xlsx")
print(read_excl)

   StudentID          FullName  Data Structure Marks  Algorithm Marks  \
0     PH1001       Alif Rahman                  85.0             85.0
1     PH1002     Fatima Akhter                  92.0             92.0
2     PH1003     Imran Hossain                  88.0             88.0
3     PH1004  Jannatul Ferdous                  78.0             78.0
4     PH1005       Kamal Uddin                   NaN              NaN
5     PH1006       Laila Begum                  75.0             75.0
6     PH1007    Mahmudul Hasan                  80.0             80.0
7     PH1008       Nadia Islam                  81.0             81.0
8     PH1009        Omar Faruq                  72.0             72.0
9     PH1010      Priya Sharma                  89.0             89.0
10    PH1011      Rahim Sheikh                   NaN              NaN
11    PH1012   Sadia Chowdhury                  85.0             85.0
12    PH1013      Tanvir Ahmed                  75.0             75.0
13    PH1014        Urmi Akter                   NaN              NaN
14    PH1015      Wahiduzzaman                  86.0             86.0
15    PH1016      Ziaur Rahman                  94.0             94.0
16    PH1017       Afsana Mimi                  90.0             90.0
17    PH1018       Babul Ahmed                  88.0             88.0
18    PH1019      Faria Rahman                   NaN              NaN
19    PH1020        Nasir Khan                  86.0             86.0

    Python Marks CompletionStatus EnrollmentDate Instructor    Location
0           88.0        Completed     2024-01-15  Mr. Karim       Dhaka
1            NaN      In Progress     2024-01-20  Ms. Salma  Chattogram
2           85.0        Completed     2024-02-10  Mr. Karim       Dhaka
3           82.0        Completed     2024-02-12  Ms. Salma      Sylhet
4           95.0      In Progress     2024-03-05  Mr. Karim  Chattogram
5           78.0        Completed     2024-03-08  Ms. Salma    Rajshahi
6            NaN      In Progress     2024-04-01  Mr. Karim       Dhaka
7           85.0        Completed     2024-04-22  Ms. Salma  Chattogram
8           76.0        Completed     2024-05-16  Mr. David       Dhaka
9           88.0        Completed     2024-05-20  Ms. Salma      Sylhet
10          91.0      In Progress     2024-06-11  Mr. Karim      Khulna
11          87.0        Completed     2024-06-14  Ms. Salma  Chattogram
12          79.0        Completed     2024-07-02  Mr. David       Dhaka
13           NaN      Not Started     2024-07-09  Ms. Salma    Rajshahi
14          84.0        Completed     2024-08-18  Mr. Karim       Dhaka
15           NaN      In Progress     2024-08-21  Ms. Salma  Chattogram
16          93.0        Completed     2025-09-01  Mr. Karim       Dhaka
17          85.0        Completed     2025-09-05  Ms. Salma      Sylhet
18           NaN      Not Started     2025-09-15  Mr. David  Chattogram
19          89.0        Completed     2025-10-02  Ms. Salma       Dhaka

In [4]:
read_parquet = pd.read_parquet("students.parquet")
print(read_parquet)

   StudentID          FullName  Data Structure Marks  Algorithm Marks  \
0     PH1001       Alif Rahman                  85.0             85.0
1     PH1002     Fatima Akhter                  92.0             92.0
2     PH1003     Imran Hossain                  88.0             88.0
3     PH1004  Jannatul Ferdous                  78.0             78.0
4     PH1005       Kamal Uddin                   NaN              NaN
5     PH1006       Laila Begum                  75.0             75.0
6     PH1007    Mahmudul Hasan                  80.0             80.0
7     PH1008       Nadia Islam                  81.0             81.0
8     PH1009        Omar Faruq                  72.0             72.0
9     PH1010      Priya Sharma                  89.0             89.0
10    PH1011      Rahim Sheikh                   NaN              NaN
11    PH1012   Sadia Chowdhury                  85.0             85.0
12    PH1013      Tanvir Ahmed                  75.0             75.0
13    PH1014        Urmi Akter                   NaN              NaN
14    PH1015      Wahiduzzaman                  86.0             86.0
15    PH1016      Ziaur Rahman                  94.0             94.0
16    PH1017       Afsana Mimi                  90.0             90.0
17    PH1018       Babul Ahmed                  88.0             88.0
18    PH1019      Faria Rahman                   NaN              NaN
19    PH1020        Nasir Khan                  86.0             86.0

    Python Marks CompletionStatus EnrollmentDate Instructor    Location
0           88.0        Completed     2024-01-15  Mr. Karim       Dhaka
1            NaN      In Progress     2024-01-20  Ms. Salma  Chattogram
2           85.0        Completed     2024-02-10  Mr. Karim       Dhaka
3           82.0        Completed     2024-02-12  Ms. Salma      Sylhet
4           95.0      In Progress     2024-03-05  Mr. Karim  Chattogram
5           78.0        Completed     2024-03-08  Ms. Salma    Rajshahi
6            NaN      In Progress     2024-04-01  Mr. Karim       Dhaka
7           85.0        Completed     2024-04-22  Ms. Salma  Chattogram
8           76.0        Completed     2024-05-16  Mr. David       Dhaka
9           88.0        Completed     2024-05-20  Ms. Salma      Sylhet
10          91.0      In Progress     2024-06-11  Mr. Karim      Khulna
11          87.0        Completed     2024-06-14  Ms. Salma  Chattogram
12          79.0        Completed     2024-07-02  Mr. David       Dhaka
13           NaN      Not Started     2024-07-09  Ms. Salma    Rajshahi
14          84.0        Completed     2024-08-18  Mr. Karim       Dhaka
15           NaN      In Progress     2024-08-21  Ms. Salma  Chattogram
16          93.0        Completed     2025-09-01  Mr. Karim       Dhaka
17          85.0        Completed     2025-09-05  Ms. Salma      Sylhet
18           NaN      Not Started     2025-09-15  Mr. David  Chattogram
19          89.0        Completed     2025-10-02  Ms. Salma       Dhaka

In [6]:
read_json = pd.read_json("data.json")
print(read_json)
print(type(read_json))

  StudentID          FullName  Data Structure Marks  Algorithm Marks  \
0    PH1001       Alif Rahman                    85               85
1    PH1002     Fatima Akhter                    92               92
2    PH1004  Jannatul Ferdous                    78               78

   Python Marks
0            88
1            90
2            82
<class 'pandas.core.frame.DataFrame'>

### Basic Functionalities

In [9]:
#  some value from the beginning

df.head(3)

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka

In [11]:
# value from the end
df.tail(3)

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

In [17]:
import numpy as np
df.columns

col = np.array(df.columns)
print(col)

['StudentID' 'FullName' 'Data Structure Marks' 'Algorithm Marks'
 'Python Marks' 'CompletionStatus' 'EnrollmentDate' 'Instructor'
 'Location']

In [19]:
df.index

ind = np.array(df.index)
print(ind)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   StudentID             20 non-null     object
 1   FullName              20 non-null     object
 2   Data Structure Marks  16 non-null     float64
 3   Algorithm Marks       16 non-null     float64
 4   Python Marks          15 non-null     float64
 5   CompletionStatus      20 non-null     object
 6   EnrollmentDate        20 non-null     object
 7   Instructor            20 non-null     object
 8   Location              20 non-null     object
dtypes: float64(3), object(6)
memory usage: 1.5+ KB

In [25]:
df.sample(5)

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram

In [26]:
# statistical values
df.describe()

       Data Structure Marks  Algorithm Marks  Python Marks
count             16.000000        16.000000     15.000000
mean              84.000000        84.000000     85.666667
std                6.501282         6.501282      5.394000
min               72.000000        72.000000     76.000000
25%               79.500000        79.500000     83.000000
50%               85.500000        85.500000     85.000000
75%               88.250000        88.250000     88.500000
max               94.000000        94.000000     95.000000

### Transforming to df from inbuilt datas

In [32]:
my_list = [['Alice', 25], ['Bob', 30], ['Charlie', 28]]

list_df = pd.DataFrame(my_list,columns = [my_tuple = (('Alice', 25), ('Bob', 30), ('Charlie', 28))
'Name','Age'],index=[1,2,3])
print(list_df)

      Name  Age
1    Alice   25
2      Bob   30
3  Charlie   28

In [33]:
my_tuple = (('Alice', 25), ('Bob', 30), ('Charlie', 28))

tuple_df = pd.DataFrame(my_tuple, columns=['Name','Age'])
print(tuple_df)

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   28

In [34]:
my_dict = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 29,28]
}

dict_df = pd.DataFrame(my_dict)
dict_df

      Name  Age
0    Alice   25
1      Bob   29
2  Charlie   28

In [35]:
my_data = [
    {'Name': 'Alice', 'Age': 25, 'City': 'New York'},
    {'Name': 'Bob', 'Age': 30, 'City': 'Paris'},
    {'Name': 'Charlie', 'Age': 28}
]

data_df = pd.DataFrame(my_data)
data_df

      Name  Age      City
0    Alice   25  New York
1      Bob   30     Paris
2  Charlie   28       NaN

### Accessing values from DF

In [79]:
df

,StudentID,FullName,DS Marks,Algo Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

In [40]:
#accessing a column

df['FullName']
print(type(df['FullName']))

<class 'pandas.core.series.Series'>

In [49]:
# df.loc[ind start:ind end,col_start,col_end]
df.loc[0]
print(df.loc[0])
print()
print(type(df.loc[0]))

StudentID                    PH1001
FullName                Alif Rahman
Data Structure Marks           85.0
Algorithm Marks                85.0
Python Marks                   88.0
CompletionStatus          Completed
EnrollmentDate           2024-01-15
Instructor                Mr. Karim
Location                      Dhaka
Name: 0, dtype: object

<class 'pandas.core.series.Series'>

In [51]:
# multiple row ( normal list ) 

df.loc[[1,6,9]]

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet

In [52]:
# multiple row ( range ) 

df.loc[3:7]

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram

In [53]:
# single column 

df.loc[:,"Algorithm Marks"]

0     85.0
1     92.0
2     88.0
3     78.0
4      NaN
5     75.0
6     80.0
7     81.0
8     72.0
9     89.0
10     NaN
11    85.0
12    75.0
13     NaN
14    86.0
15    94.0
16    90.0
17    88.0
18     NaN
19    86.0
Name: Algorithm Marks, dtype: float64

In [59]:
#multiple column 

df.loc[:,['Data Structure Marks','Algorithm Marks']]
# print(type(df.loc[:,['Data Structure Marks','Algorithm Marks']]))

    Data Structure Marks  Algorithm Marks
0                   85.0             85.0
1                   92.0             92.0
2                   88.0             88.0
3                   78.0             78.0
4                    NaN              NaN
5                   75.0             75.0
6                   80.0             80.0
7                   81.0             81.0
8                   72.0             72.0
9                   89.0             89.0
10                   NaN              NaN
11                  85.0             85.0
12                  75.0             75.0
13                   NaN              NaN
14                  86.0             86.0
15                  94.0             94.0
16                  90.0             90.0
17                  88.0             88.0
18                   NaN              NaN
19                  86.0             86.0

In [60]:
df.loc[1:5,['Data Structure Marks','Algorithm Marks']]

   Data Structure Marks  Algorithm Marks
1                  92.0             92.0
2                  88.0             88.0
3                  78.0             78.0
4                   NaN              NaN
5                  75.0             75.0

### Changing index and columns and iloc

In [63]:
df_index = df.set_index('StudentID')
df_index

,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
StudentID,,,,,,,,
PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

In [72]:
df_index.iloc[1:5,0:5]

,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus
StudentID,,,,,
PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress
PH1003,Imran Hossain,88.0,88.0,85.0,Completed
PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed
PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress

In [74]:
df.rename(columns={'Data Structure Marks':'DS Marks','Algorithm Marks':'Algo Marks'},inplace=True)
df

,StudentID,FullName,DS Marks,Algo Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

### Changing values and Iteration

In [75]:
df

,StudentID,FullName,DS Marks,Algo Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

In [ ]:
# row deletion
df.drop(0,inplace=True)

In [85]:
df

,StudentID,FullName,DS Marks,Algo Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

In [ ]:
df.drop('Instructor',axis=1,inplace=True)

In [88]:
df

,StudentID,FullName,DS Marks,Algo Marks,Python Marks,CompletionStatus,EnrollmentDate,Location
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Dhaka

In [96]:
df.loc[1,'Python Marks'] = 90
df.loc[1,'CompletionStatus'] = 'Completed'
df.head()

,StudentID,FullName,DS Marks,Algo Marks,Python Marks,CompletionStatus,EnrollmentDate,Location
1,PH1002,Fatima Akhter,92.0,92.0,90.0,Completed,2024-01-20,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Rajshahi

In [112]:
df.loc[1:5,'Python Marks']+=2
df.head()

,StudentID,FullName,DS Marks,Algo Marks,Python Marks,CompletionStatus,EnrollmentDate,Location
1,PH1002,Fatima Akhter,92.0,92.0,106.0,Completed,2024-01-20,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,101.0,Completed,2024-02-10,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,98.0,Completed,2024-02-12,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,109.0,In Progress,2024-03-05,Chattogram
5,PH1006,Laila Begum,75.0,75.0,92.0,Completed,2024-03-08,Rajshahi

In [113]:
for i,series in df.iterrows():
    print(f"{i} : {series}")

1 : StudentID                  PH1002
FullName            Fatima Akhter
DS Marks                     92.0
Algo Marks                   92.0
Python Marks                106.0
CompletionStatus        Completed
EnrollmentDate         2024-01-20
Location               Chattogram
Name: 1, dtype: object
2 : StudentID                  PH1003
FullName            Imran Hossain
DS Marks                     88.0
Algo Marks                   88.0
Python Marks                101.0
CompletionStatus        Completed
EnrollmentDate         2024-02-10
Location                    Dhaka
Name: 2, dtype: object
3 : StudentID                     PH1004
FullName            Jannatul Ferdous
DS Marks                        78.0
Algo Marks                      78.0
Python Marks                    98.0
CompletionStatus           Completed
EnrollmentDate            2024-02-12
Location                      Sylhet
Name: 3, dtype: object
4 : StudentID                PH1005
FullName            Kamal Uddin
DS Marks                    NaN
Algo Marks                  NaN
Python Marks              109.0
CompletionStatus    In Progress
EnrollmentDate       2024-03-05
Location             Chattogram
Name: 4, dtype: object
5 : StudentID                PH1006
FullName            Laila Begum
DS Marks                   75.0
Algo Marks                 75.0
Python Marks               92.0
CompletionStatus      Completed
EnrollmentDate       2024-03-08
Location               Rajshahi
Name: 5, dtype: object
6 : StudentID                   PH1007
FullName            Mahmudul Hasan
DS Marks                      80.0
Algo Marks                    80.0
Python Marks                   NaN
CompletionStatus       In Progress
EnrollmentDate          2024-04-01
Location                     Dhaka
Name: 6, dtype: object
7 : StudentID                PH1008
FullName            Nadia Islam
DS Marks                   81.0
Algo Marks                 81.0
Python Marks               85.0
CompletionStatus      Completed
EnrollmentDate       2024-04-22
Location             Chattogram
Name: 7, dtype: object
8 : StudentID               PH1009
FullName            Omar Faruq
DS Marks                  72.0
Algo Marks                72.0
Python Marks              76.0
CompletionStatus     Completed
EnrollmentDate      2024-05-16
Location                 Dhaka
Name: 8, dtype: object
9 : StudentID                 PH1010
FullName            Priya Sharma
DS Marks                    89.0
Algo Marks                  89.0
Python Marks                88.0
CompletionStatus       Completed
EnrollmentDate        2024-05-20
Location                  Sylhet
Name: 9, dtype: object
10 : StudentID                 PH1011
FullName            Rahim Sheikh
DS Marks                     NaN
Algo Marks                   NaN
Python Marks                91.0
CompletionStatus     In Progress
EnrollmentDate        2024-06-11
Location                  Khulna
Name: 10, dtype: object
11 : StudentID                    PH1012
FullName            Sadia Chowdhury
DS Marks                       85.0
Algo Marks                     85.0
Python Marks                   87.0
CompletionStatus          Completed
EnrollmentDate           2024-06-14
Location                 Chattogram
Name: 11, dtype: object
12 : StudentID                 PH1013
FullName            Tanvir Ahmed
DS Marks                    75.0
Algo Marks                  75.0
Python Marks                79.0
CompletionStatus       Completed
EnrollmentDate        2024-07-02
Location                   Dhaka
Name: 12, dtype: object
13 : StudentID                PH1014
FullName             Urmi Akter
DS Marks                    NaN
Algo Marks                  NaN
Python Marks                NaN
CompletionStatus    Not Started
EnrollmentDate       2024-07-09
Location               Rajshahi
Name: 13, dtype: object
14 : StudentID                 PH1015
FullName            Wahiduzzaman
DS Marks                    86.0
Algo Marks                  86.0
Python Marks                84.0
CompletionStatus       Completed
EnrollmentDate        2024-08-18
Location                   Dhaka
Name: 14, dtype: object
15 : StudentID                 PH1016
FullName            Ziaur Rahman
DS Marks                    94.0
Algo Marks                  94.0
Python Marks                 NaN
CompletionStatus     In Progress
EnrollmentDate        2024-08-21
Location              Chattogram
Name: 15, dtype: object
16 : StudentID                PH1017
FullName            Afsana Mimi
DS Marks                   90.0
Algo Marks                 90.0
Python Marks               93.0
CompletionStatus      Completed
EnrollmentDate       2025-09-01
Location                  Dhaka
Name: 16, dtype: object
17 : StudentID                PH1018
FullName            Babul Ahmed
DS Marks                   88.0
Algo Marks                 88.0
Python Marks               85.0
CompletionStatus      Completed
EnrollmentDate       2025-09-05
Location                 Sylhet
Name: 17, dtype: object
18 : StudentID                 PH1019
FullName            Faria Rahman
DS Marks                     NaN
Algo Marks                   NaN
Python Marks                 NaN
CompletionStatus     Not Started
EnrollmentDate        2025-09-15
Location              Chattogram
Name: 18, dtype: object
19 : StudentID               PH1020
FullName            Nasir Khan
DS Marks                  86.0
Algo Marks                86.0
Python Marks              89.0
CompletionStatus     Completed
EnrollmentDate      2025-10-02
Location                 Dhaka
Name: 19, dtype: object
Python Marks : StudentID             90
FullName              90
DS Marks            90.0
Algo Marks          90.0
Python Marks        90.0
CompletionStatus      90
EnrollmentDate        90
Location              90
Name: Python Marks, dtype: object

In [120]:
for i in df.itertuples(index=False):
    print(i)

Pandas(StudentID='PH1002', FullName='Fatima Akhter', _2=92.0, _3=92.0, _4=106.0, CompletionStatus='Completed', EnrollmentDate='2024-01-20', Location='Chattogram')
Pandas(StudentID='PH1003', FullName='Imran Hossain', _2=88.0, _3=88.0, _4=101.0, CompletionStatus='Completed', EnrollmentDate='2024-02-10', Location='Dhaka')
Pandas(StudentID='PH1004', FullName='Jannatul Ferdous', _2=78.0, _3=78.0, _4=98.0, CompletionStatus='Completed', EnrollmentDate='2024-02-12', Location='Sylhet')
Pandas(StudentID='PH1005', FullName='Kamal Uddin', _2=nan, _3=nan, _4=109.0, CompletionStatus='In Progress', EnrollmentDate='2024-03-05', Location='Chattogram')
Pandas(StudentID='PH1006', FullName='Laila Begum', _2=75.0, _3=75.0, _4=92.0, CompletionStatus='Completed', EnrollmentDate='2024-03-08', Location='Rajshahi')
Pandas(StudentID='PH1007', FullName='Mahmudul Hasan', _2=80.0, _3=80.0, _4=nan, CompletionStatus='In Progress', EnrollmentDate='2024-04-01', Location='Dhaka')
Pandas(StudentID='PH1008', FullName='Nadia Islam', _2=81.0, _3=81.0, _4=85.0, CompletionStatus='Completed', EnrollmentDate='2024-04-22', Location='Chattogram')
Pandas(StudentID='PH1009', FullName='Omar Faruq', _2=72.0, _3=72.0, _4=76.0, CompletionStatus='Completed', EnrollmentDate='2024-05-16', Location='Dhaka')
Pandas(StudentID='PH1010', FullName='Priya Sharma', _2=89.0, _3=89.0, _4=88.0, CompletionStatus='Completed', EnrollmentDate='2024-05-20', Location='Sylhet')
Pandas(StudentID='PH1011', FullName='Rahim Sheikh', _2=nan, _3=nan, _4=91.0, CompletionStatus='In Progress', EnrollmentDate='2024-06-11', Location='Khulna')
Pandas(StudentID='PH1012', FullName='Sadia Chowdhury', _2=85.0, _3=85.0, _4=87.0, CompletionStatus='Completed', EnrollmentDate='2024-06-14', Location='Chattogram')
Pandas(StudentID='PH1013', FullName='Tanvir Ahmed', _2=75.0, _3=75.0, _4=79.0, CompletionStatus='Completed', EnrollmentDate='2024-07-02', Location='Dhaka')
Pandas(StudentID='PH1014', FullName='Urmi Akter', _2=nan, _3=nan, _4=nan, CompletionStatus='Not Started', EnrollmentDate='2024-07-09', Location='Rajshahi')
Pandas(StudentID='PH1015', FullName='Wahiduzzaman', _2=86.0, _3=86.0, _4=84.0, CompletionStatus='Completed', EnrollmentDate='2024-08-18', Location='Dhaka')
Pandas(StudentID='PH1016', FullName='Ziaur Rahman', _2=94.0, _3=94.0, _4=nan, CompletionStatus='In Progress', EnrollmentDate='2024-08-21', Location='Chattogram')
Pandas(StudentID='PH1017', FullName='Afsana Mimi', _2=90.0, _3=90.0, _4=93.0, CompletionStatus='Completed', EnrollmentDate='2025-09-01', Location='Dhaka')
Pandas(StudentID='PH1018', FullName='Babul Ahmed', _2=88.0, _3=88.0, _4=85.0, CompletionStatus='Completed', EnrollmentDate='2025-09-05', Location='Sylhet')
Pandas(StudentID='PH1019', FullName='Faria Rahman', _2=nan, _3=nan, _4=nan, CompletionStatus='Not Started', EnrollmentDate='2025-09-15', Location='Chattogram')
Pandas(StudentID='PH1020', FullName='Nasir Khan', _2=86.0, _3=86.0, _4=89.0, CompletionStatus='Completed', EnrollmentDate='2025-10-02', Location='Dhaka')
Pandas(StudentID=90, FullName=90, _2=90.0, _3=90.0, _4=90.0, CompletionStatus=90, EnrollmentDate=90, Location=90)

### Sorting

In [122]:
df

,StudentID,FullName,DS Marks,Algo Marks,Python Marks,CompletionStatus,EnrollmentDate,Location
1,PH1002,Fatima Akhter,92.0,92.0,106.0,Completed,2024-01-20,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,101.0,Completed,2024-02-10,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,98.0,Completed,2024-02-12,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,109.0,In Progress,2024-03-05,Chattogram
5,PH1006,Laila Begum,75.0,75.0,92.0,Completed,2024-03-08,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Dhaka
Python Marks,90,90,90.0,90.0,90.0,90,90,90

In [124]:
cpy = df.sort_values('DS Marks')
cpy

,StudentID,FullName,DS Marks,Algo Marks,Python Marks,CompletionStatus,EnrollmentDate,Location
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Chattogram
1,PH1002,Fatima Akhter,92.0,92.0,106.0,Completed,2024-01-20,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Dhaka
Python Marks,90,90,90.0,90.0,90.0,90,90,90
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Sylhet
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Sylhet
2,PH1003,Imran Hossain,88.0,88.0,101.0,Completed,2024-02-10,Dhaka
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Dhaka
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Dhaka
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Chattogram
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Chattogram
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,98.0,Completed,2024-02-12,Sylhet
5,PH1006,Laila Begum,75.0,75.0,92.0,Completed,2024-03-08,Rajshahi
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Dhaka
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Dhaka
4,PH1005,Kamal Uddin,NaN,NaN,109.0,In Progress,2024-03-05,Chattogram
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Khulna
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Rajshahi
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Chattogram

In [125]:
cpy = df.sort_values('DS Marks',ascending=False)
cpy

,StudentID,FullName,DS Marks,Algo Marks,Python Marks,CompletionStatus,EnrollmentDate,Location
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Chattogram
1,PH1002,Fatima Akhter,92.0,92.0,106.0,Completed,2024-01-20,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Dhaka
Python Marks,90,90,90.0,90.0,90.0,90,90,90
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Sylhet
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Sylhet
2,PH1003,Imran Hossain,88.0,88.0,101.0,Completed,2024-02-10,Dhaka
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Dhaka
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Dhaka
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Chattogram
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Chattogram
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,98.0,Completed,2024-02-12,Sylhet
5,PH1006,Laila Begum,75.0,75.0,92.0,Completed,2024-03-08,Rajshahi
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Dhaka
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Dhaka
4,PH1005,Kamal Uddin,NaN,NaN,109.0,In Progress,2024-03-05,Chattogram
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Khulna
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Rajshahi
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Chattogram

In [126]:
cpy = df.sort_values(['DS Marks','Python Marks'],ascending=False)
cpy

,StudentID,FullName,DS Marks,Algo Marks,Python Marks,CompletionStatus,EnrollmentDate,Location
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Chattogram
1,PH1002,Fatima Akhter,92.0,92.0,106.0,Completed,2024-01-20,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Dhaka
Python Marks,90,90,90.0,90.0,90.0,90,90,90
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Sylhet
2,PH1003,Imran Hossain,88.0,88.0,101.0,Completed,2024-02-10,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Sylhet
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Dhaka
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Dhaka
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Chattogram
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Chattogram
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,98.0,Completed,2024-02-12,Sylhet
5,PH1006,Laila Begum,75.0,75.0,92.0,Completed,2024-03-08,Rajshahi
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Dhaka
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Dhaka
4,PH1005,Kamal Uddin,NaN,NaN,109.0,In Progress,2024-03-05,Chattogram
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Khulna
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Rajshahi
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Chattogram

In [127]:
cpy = df.sort_values(['DS Marks','Python Marks'],ascending=[0,1])
cpy

,StudentID,FullName,DS Marks,Algo Marks,Python Marks,CompletionStatus,EnrollmentDate,Location
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Chattogram
1,PH1002,Fatima Akhter,92.0,92.0,106.0,Completed,2024-01-20,Chattogram
Python Marks,90,90,90.0,90.0,90.0,90,90,90
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Sylhet
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Sylhet
2,PH1003,Imran Hossain,88.0,88.0,101.0,Completed,2024-02-10,Dhaka
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Dhaka
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Dhaka
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Chattogram
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Chattogram
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,98.0,Completed,2024-02-12,Sylhet
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Dhaka
5,PH1006,Laila Begum,75.0,75.0,92.0,Completed,2024-03-08,Rajshahi
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Dhaka
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Khulna
4,PH1005,Kamal Uddin,NaN,NaN,109.0,In Progress,2024-03-05,Chattogram
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Rajshahi
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Chattogram

### Filtering data based on condition

In [129]:
not_started = df.loc[df['CompletionStatus'] == 'Not Started']
not_started

,StudentID,FullName,DS Marks,Algo Marks,Python Marks,CompletionStatus,EnrollmentDate,Location
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Rajshahi
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Chattogram

In [130]:
completed = df.loc[df['CompletionStatus'] == 'Completed']
completed

,StudentID,FullName,DS Marks,Algo Marks,Python Marks,CompletionStatus,EnrollmentDate,Location
1,PH1002,Fatima Akhter,92.0,92.0,106.0,Completed,2024-01-20,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,101.0,Completed,2024-02-10,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,98.0,Completed,2024-02-12,Sylhet
5,PH1006,Laila Begum,75.0,75.0,92.0,Completed,2024-03-08,Rajshahi
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Sylhet
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Dhaka
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Dhaka
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Sylhet
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Dhaka

In [132]:
res =df.loc[(df['CompletionStatus'] == 'Completed') & (df['DS Marks'] >= 90)]
res

,StudentID,FullName,DS Marks,Algo Marks,Python Marks,CompletionStatus,EnrollmentDate,Location
1,PH1002,Fatima Akhter,92.0,92.0,106.0,Completed,2024-01-20,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Dhaka