In [7]:
import pandas as pd

data = {
    "Name":["Alice", "Bob", "Charlie"],
    "Age":[25,30,35],
    "City":["York New", "London", "paris"]
}

df = pd.DataFrame(data)
df

      Name  Age      City
0    Alice   25  York New
1      Bob   30    London
2  Charlie   35     paris

In [8]:
df.loc[df['City'].str.contains("New")]

    Name  Age      City
0  Alice   25  York New

In [4]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'A': [1, 2, np.nan, 4, 5],
    'B': [5, np.nan, np.nan, None, 10],
    'C': ['a', 'b', 'c', None, 'e']
})
                   
print(df)

     A     B     C
0  1.0   5.0     a
1  2.0   NaN     b
2  NaN   NaN     c
3  4.0   NaN  None
4  5.0  10.0     e

In [11]:
df_filled1 = df.fillna({'A':0, 'B': 99, 'C':'Unknown'})
df_filled1

     A     B        C
0  1.0   5.0        a
1  2.0  99.0        b
2  0.0  99.0        c
3  4.0  99.0  Unknown
4  5.0  10.0        e

In [12]:
df_ff = df.copy()
df_ff["B"] = df_ff["B"].ffill()
print(df_ff)

     A     B     C
0  1.0   5.0     a
1  2.0   5.0     b
2  0.0   5.0     c
3  4.0   5.0  None
4  5.0  10.0     e

In [18]:
for column in df.columns:
    if df[column].dtype == "object":
        df[column].fillna("Unknown", inplace=True)
    else:
        df[column].fillna(df[column].mean(), inplace=True)
df

C:\Users\GIGABYTE\AppData\Local\Temp\ipykernel_2864\1965914591.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[column].fillna(df[column].mean(), inplace=True)

     A     B        C
0  1.0   5.0        a
1  2.0   7.5        b
2  0.0   7.5        c
3  4.0   7.5  Unknown
4  5.0  10.0        e

In [20]:
df = pd.DataFrame({
    'A': [1, 2, np.nan, 4, 5],
    'B': [5, np.nan, np.nan, None, 10],
    'C': ['a', 'b', 'c', None, 'e']
})

# Drop rows where column A has missing values
df_a = df.dropna(subset=["A"])

print(df_a)

     A     B     C
0  1.0   5.0     a
1  2.0   NaN     b
3  4.0   NaN  None
4  5.0  10.0     e

In [21]:
df_clean = df.dropna(thresh=2)
print(df_clean)

     A     B  C
0  1.0   5.0  a
1  2.0   NaN  b
4  5.0  10.0  e

In [26]:
df_clean = df.dropna(subset=["A","B"], how="all")
print(df_clean)

     A     B     C
0  1.0   5.0     a
1  2.0   NaN     b
3  4.0   NaN  None
4  5.0  10.0     e

In [27]:
df = pd.DataFrame({
    'A': [1, 2, np.nan, 4, 5],
    'B': [5, np.nan, np.nan, None, 10],
    'C': ['a', 'b', 'c', None, 'e']
})
                   
print(df)

     A     B     C
0  1.0   5.0     a
1  2.0   NaN     b
2  NaN   NaN     c
3  4.0   NaN  None
4  5.0  10.0     e

In [28]:
df_clean = df.dropna(thresh=2)
print(df_clean)

     A     B  C
0  1.0   5.0  a
1  2.0   NaN  b
4  5.0  10.0  e

In [30]:
df = pd.read_csv('student_data.csv') 
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [35]:
status  = df.groupby("CompletionStatus")
status.size()

CompletionStatus
Completed      13
In Progress     5
Not Started     2
dtype: int64

In [36]:
status  = df.groupby("Location")
status.size()

Location
Chattogram    6
Dhaka         8
Khulna        1
Rajshahi      2
Sylhet        3
dtype: int64

In [39]:
status  = df.groupby("Location").size()
print(status.index)
status.values

Index(['Chattogram', 'Dhaka', 'Khulna', 'Rajshahi', 'Sylhet'], dtype='object', name='Location')

array([6, 8, 1, 2, 3])