In [1]:
import numpy as np
import pandas as pd

np.random.seed(42)

ids = np.arange(1, 11)
ages = np.random.randint(18, 60, 10)
salaries = np.random.randint(30000, 90000, 10)
departments = np.array(["HR", "IT", "Finance", "IT", "HR", "Sales", "Finance", "IT", "Sales", "HR"])

DF = pd.DataFrame({
"id": ids,
"age": ages,
"salary": salaries,
"dept": departments
})

DF.to_csv("employees.csv", index=False)
print("Sample Data Created and Saved as employees.csv")

Sample Data Created and Saved as employees.csv

In [10]:
# 1 

ages = np.array(ages)
print(ages)
print(ages.dtype)
print(ages.ndim)
print(ages.shape)
print(ages.size)

print("-"*30)



salaries = np.array(salaries)
print(salaries)
print(salaries.dtype)
print(salaries.ndim)
print(salaries.shape)
print(salaries.size)

[56 46 32 25 38 56 36 40 28 28]
int32
1
(10,)
10
------------------------------
[77191 74131 46023 71090 31685 30769 89735 86101 32433 35311]
int32
1
(10,)
10

In [14]:
# 2
print(salaries)
highest_salary = np.max(salaries)
lowest_salaries = np.min(salaries)
avg_salary = np.average(salaries)

print("Highest salary ",highest_salary)
print("Lowest salary: ",lowest_salaries)
print("Average salary: ",avg_salary)

average_age = np.average(ages)
print("Average age: ",average_age)

[77191 74131 46023 71090 31685 30769 89735 86101 32433 35311]
Highest salary  89735
Lowest salary:  30769
Average salary:  57446.9
Average age:  38.5

In [27]:
# 3
print(ages)
age_greater_than_30 = ages[ages>30]
print(age_greater_than_30)
age_greater_than_30_count = np.count_nonzero(ages>30)
print(age_greater_than_30_count)

[56 46 32 25 38 56 36 40 28 28]
[56 46 32 38 56 36 40]
7

In [30]:
# 4
new_arra = ages+5
print(new_arra)

[61 51 37 30 43 61 41 45 33 33]

In [34]:
# 5
total_salary = np.sum(salaries)
print("Total salary: ",total_salary)

diff = np.max(salaries) - np.min(salaries)
print("Difference between highest and lowest salary: ",diff)

Total salary:  574469
Difference between highest and lowest salary:  58966

In [1]:
# 6
import pandas as pd
df = pd.read_csv("employees.csv")
print(df)

   id  age  salary     dept
0   1   56   77191       HR
1   2   46   74131       IT
2   3   32   46023  Finance
3   4   25   71090       IT
4   5   38   31685       HR
5   6   56   30769    Sales
6   7   36   89735  Finance
7   8   40   86101       IT
8   9   28   32433    Sales
9  10   28   35311       HR

In [36]:
df.head(5)

   id  age  salary     dept
0   1   56   77191       HR
1   2   46   74131       IT
2   3   32   46023  Finance
3   4   25   71090       IT
4   5   38   31685       HR

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      10 non-null     int64
 1   age     10 non-null     int64
 2   salary  10 non-null     int64
 3   dept    10 non-null     object
dtypes: int64(3), object(1)
memory usage: 452.0+ bytes

In [41]:
df.describe()

             id       age        salary
count  10.00000  10.00000     10.000000
mean    5.50000  38.50000  57446.900000
std     3.02765  11.16791  24357.262884
min     1.00000  25.00000  30769.000000
25%     3.25000  29.00000  33152.500000
50%     5.50000  37.00000  58556.500000
75%     7.75000  44.50000  76426.000000
max    10.00000  56.00000  89735.000000

In [44]:
# 7
list_df = pd.DataFrame(df, columns=['id','age','salary'])
print(list_df)

   id  age  salary
0   1   56   77191
1   2   46   74131
2   3   32   46023
3   4   25   71090
4   5   38   31685
5   6   56   30769
6   7   36   89735
7   8   40   86101
8   9   28   32433
9  10   28   35311

In [45]:
print(list_df.tail(3))

   id  age  salary
7   8   40   86101
8   9   28   32433
9  10   28   35311

In [51]:
# 8
res = df[df['dept'] == 'IT']
print(res)

   id  age  salary dept
1   2   46   74131   IT
3   4   25   71090   IT
7   8   40   86101   IT

In [58]:
print("Total number: ",len(res))

Total number:  3

In [59]:
# 9
res = df.sort_values('salary', ascending=False)
print(res)

   id  age  salary     dept
6   7   36   89735  Finance
7   8   40   86101       IT
0   1   56   77191       HR
1   2   46   74131       IT
3   4   25   71090       IT
2   3   32   46023  Finance
9  10   28   35311       HR
8   9   28   32433    Sales
4   5   38   31685       HR
5   6   56   30769    Sales

In [60]:
res.head(3)

   id  age  salary     dept
6   7   36   89735  Finance
7   8   40   86101       IT
0   1   56   77191       HR

In [67]:
# 10
df.loc[df['salary'] > 80000,'salary'] = 80000

   id  age  salary     dept
0   1   56   77191       HR
1   2   46   74131       IT
2   3   32   46023  Finance
3   4   25   71090       IT
4   5   38   31685       HR
5   6   56   30769    Sales
6   7   36   80000  Finance
7   8   40   80000       IT
8   9   28   32433    Sales
9  10   28   35311       HR

In [76]:
res = df['salary']
print("New average salary: ",res.sum()/len(res))

New average salary:  55863.3